#!/usr/bin/env python

import webbrowser, sys, requests, bs4, time
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.keys import Keys

def wait_for(condition_function):
  start_time = time.time()
  while time.time() < start_time + 3:
    if condition_function():
      return True
    else:
      time.sleep(0.1)
  raise Exception('Timeout')

def click_through_to_new_page(elem):
  elem.click()

  def link_has_gone_stale():
    try:
      # poll the link with an arbitrary call
      elem.find_elements_by_id('doesnt-matter')
      return False
    except StaleElementReferenceException:
      return True

  wait_for(link_has_gone_stale)

def process_data(br, n):
    attractions = br.find_elements_by_class_name('attraction_element')
    print len(attractions)
    to_present = n
    print to_present

    for e in attractions:
        to_present -= 1
        if to_present < 0:
            break
          
        print e.find_element_by_tag_name('a').get_attribute('href')
        e.find_element_by_tag_name('a').send_keys(Keys.CONTROL + Keys.RETURN)

    if to_present >= 0:
        pagination = None
        nxt = None
        try:
            br.find_element_by_class_name('pagination')
            nxt = br.find_element_by_link_text('Next')
        except NoSuchElementException:
            return
        click_through_to_new_page(nxt)
        process_data(br, to_present)

arg = ''
if len(sys.argv) > 1:
    arg = sys.argv[1]
else:
    print 'Argument required'
    sys.exit()


br = webdriver.Chrome()
br.get('http://tripadvisor.com/Attractions')

inputs = br.find_elements_by_class_name('typeahead_input')
main_input = inputs[0]
main_input.send_keys(arg)
click_through_to_new_page(br.find_elements_by_id('SUBMIT_THINGS_TO_DO')[0])

to_present = 10
if len(sys.argv) > 2:
    to_present = int(sys.argv[2])
